# N-D Arrays
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

In [2]:
import numpy as np

In [2]:
lst1 = range(1000)
%timeit [i**2 for i in lst1]

340 µs ± 2.49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
lst2 = np.arange(1000)
%timeit lst2**2

1.61 µs ± 15.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creating Arrays

In [4]:
# 1-D Arrays
            #numpy array takes homogenous elements as input unlike lists in python
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [6]:
len(arr)

5

In [7]:
arr.ndim #dimensions

1

In [8]:
arr.shape

(5,)

In [9]:
#2D Arrays

arr = np.array([[0, 1, 2], [3, 4, 5]])

print(arr)

[[0 1 2]
 [3 4 5]]


In [10]:
type(arr)

numpy.ndarray

In [11]:
len(arr)

2

In [12]:
arr.ndim

2

In [13]:
arr.shape

(2, 3)

In [4]:
#3D Array

arr = np.array([ [ [1,2],[3,4] ], [ [5,6],[7,8] ] ])

print(arr)
print("------------")
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------
(2, 2, 2)


In [15]:
type(arr)

numpy.ndarray

In [16]:
len(arr)

2

In [17]:
arr.ndim

3

In [18]:
arr.shape

(2, 2, 2)

##### Functions for Creating Arrays

In [19]:
arr = np.arange(10) #Return evenly spaced values within a given interval.

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr = np.arange(1,10,2)

In [23]:
print(arr)

[1 3 5 7 9]


In [24]:
arr = np.linspace(1, 10) #Return evenly spaced numbers over a specified interval.

In [25]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
arr = np.linspace(1, 10, 5)

In [27]:
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
arr = np.ones( (2,2) ) #Return a new array of given shape and type, filled with ones.

In [29]:
arr

array([[1., 1.],
       [1., 1.]])

In [30]:
arr = np.ones(5)

arr

array([1., 1., 1., 1., 1.])

In [31]:
arr = np.ones( (4,3) )

arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.zeros( (2,2) ) #Return a new array of given shape and type, filled with zeros.

arr

array([[0., 0.],
       [0., 0.]])

In [33]:
arr = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

arr

array([0., 0., 0., 0., 0.])

In [36]:
arr = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
arr.dtype

dtype('float64')

In [38]:
arr = np.eye(2, dtype="int8")

print(arr)

[[1 0]
 [0 1]]


In [39]:
arr.dtype

dtype('int8')

In [40]:
arr = np.eye(2,3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [41]:
arr = np.diag([1, 2, 3]) #construct a diagonal array or Extract a diagonal 

arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [42]:
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [43]:
np.diag(arr) #Extract a diagonal 

array([1, 2, 3])

In [44]:
arr = np.random.rand(5)#Random values random samples from a uniform distribution in a given shape.

arr

array([0.10914222, 0.98114725, 0.46231835, 0.26622005, 0.31447366])

In [45]:
arr = np.random.rand(3,2)

arr

array([[0.36338398, 0.9756831 ],
       [0.946457  , 0.89104967],
       [0.12336205, 0.63627359]])

In [46]:
arr = np.random.randn(5)#Return a sample (or samples) from the "standard normal" distribution.

arr

array([ 0.03087057, -0.56557663, -0.40929131, -0.63286307, -0.25601974])

In [47]:
arr = np.random.randn(2,3)

arr

array([[-0.13412922, -0.31421105,  1.36313523],
       [ 1.69343808,  0.50906281,  0.50929207]])

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/doc/stable/user/quickstart.html#array-creation">https://numpy.org/doc/stable/user/quickstart.html#array-creation</a><br>