# Datatypes
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>
NumPy supports a much greater variety of numerical types than Python does.

<img src="numpy_datatypes.jpg" width=600 height=500/>

In [1]:
import numpy as np

arr = np.arange(10)

arr.dtype

dtype('int32')

In [2]:
arr = np.arange(10, dtype="float64") #You can explicitly specify the datatype

In [3]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
arr.dtype

dtype('float64')

In [5]:
#The default data type is float for zeros and ones function

arr = np.zeros( (4,4) )  # zeros(shape, dtype=float, order='C')

In [6]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr.dtype

dtype('float64')

In [8]:
arr = np.ones(5)

print(arr)

arr.dtype

[1. 1. 1. 1. 1.]


dtype('float64')

In [9]:
#Complex datatype

arr = np.array([1+2j, 2+4j])
print(arr)
print(arr.dtype)

[1.+2.j 2.+4.j]
complex128


In [10]:
#Boolean datatype

arr = np.array([True, False, True, False])
print(arr)
print(arr.dtype)

[ True False  True False]
bool


In [11]:
arr = np.array(['wonkycode', 'wonkynerd', 'Rohit'])

print(arr.dtype)

<U9


In [12]:
length_checker = np.vectorize(len) 
arr_len = length_checker(arr) 
print(arr_len) 
print(arr_len.max()) 

[9 9 5]
9


**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/devdocs/user/basics.types.html">https://numpy.org/devdocs/user/basics.types.html</a><br>