# Indexing, Slicing and Iterating
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [1]:
import numpy as np

arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr[3] #get value by index

3

In [3]:
arr[3] = 100 #assigning to an index

In [4]:
print(arr)

[  0   1   2 100   4   5   6   7   8   9]


In [5]:
arr[2:8]

array([  2, 100,   4,   5,   6,   7])

In [6]:
arr[0:10:2] #slicing

array([0, 2, 4, 6, 8])

In [7]:
arr[0:10:2] = 500

In [8]:
print(arr)

[500   1 500 100 500   5 500   7 500   9]


In [9]:
arr[::-1]

array([  9, 500,   7, 500,   5, 500, 100, 500,   1, 500])

In [10]:
for i in arr:
    print(i)     #iterating over array

500
1
500
100
500
5
500
7
500
9


**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas

**Iterating** over multidimensional arrays is done with respect to the first axis

In [11]:
def nums(x,y):
    return 10*x+y

In [12]:
arr = np.fromfunction(nums,(5,5), dtype="int")

In [13]:
arr

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [14]:
arr[2]          #indexing

array([20, 21, 22, 23, 24])

In [15]:
arr[-1]

array([40, 41, 42, 43, 44])

In [16]:
arr[2,3]

23

In [17]:
arr[2,3] = 100 # assigning

In [18]:
arr

array([[  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 20,  21,  22, 100,  24],
       [ 30,  31,  32,  33,  34],
       [ 40,  41,  42,  43,  44]])

In [19]:
arr[1,2] #slicing a particular value.       #[row, column]

12

In [20]:
arr[0:3, 2] #slicing some values from particular column

array([ 2, 12, 22])

In [21]:
arr[:, 2]  #slicing all values from particular column

array([ 2, 12, 22, 32, 42])

In [22]:
arr[3, 2:5] #slicing some values from a particular row

array([32, 33, 34])

In [23]:
arr[3, :] #slicing all values from a particular row

array([30, 31, 32, 33, 34])

In [24]:
print(arr)

[[  0   1   2   3   4]
 [ 10  11  12  13  14]
 [ 20  21  22 100  24]
 [ 30  31  32  33  34]
 [ 40  41  42  43  44]]


In [25]:
#3D arrays

arr = np.array( [ [[  0,  1,  2],[ 10, 12, 13]], [[100,101,102],[110,112,113]] ] )

In [26]:
arr.shape

(2, 2, 3)

In [27]:
arr[0,1,1] #indexing

12

In [28]:
arr[1,1,0] = 500 #assigning

In [29]:
arr

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [500, 112, 113]]])

In [30]:
arr[:, :, :] #slicing

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [500, 112, 113]]])

In [31]:
arr[1:, :, :]  #slicing axis

array([[[100, 101, 102],
        [500, 112, 113]]])

In [32]:
arr[1:, 0:1, :] # slicing rows

array([[[100, 101, 102]]])

In [33]:
arr[1:, 0:1, 1:] #slicing particular values in a row

array([[[101, 102]]])

In [34]:
arr[0, :, 1] #slicing particular values in column

array([ 1, 12])

In [35]:
arr[:, 1, :] #slicing only a particular row in all axis

array([[ 10,  12,  13],
       [500, 112, 113]])

In [36]:
arr[:, :, 2] #slicing only a particular column in all axis

array([[  2,  13],
       [102, 113]])

In [37]:
for row in arr:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [500 112 113]]


In [38]:
for row in arr.flat:
    print(row)

0
1
2
10
12
13
100
101
102
500
112
113


<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating">https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating</a><br>