# Advance Indexing
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>
NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

In [1]:
import numpy as np

##### Using Boolean Mask

In [2]:
arr = np.array([10, 15, 25, 34, 64, 58, 79, 99, 87, 88])

In [3]:
arr

array([10, 15, 25, 34, 64, 58, 79, 99, 87, 88])

In [4]:
mask = (arr % 2 == 0)

In [5]:
mask

array([ True, False, False,  True,  True,  True, False, False, False,
        True])

In [6]:
arr[mask]

array([10, 34, 64, 58, 88])

Indexing with a mask can be very useful to assign a new value to a sub-array

In [7]:
arr[mask] = 100

In [8]:
arr

array([100,  15,  25, 100, 100, 100,  79,  99,  87, 100])

##### Indexing with an array of integers

In [9]:
arr = np.arange(0, 100, 10)

In [10]:
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Indexing can be done with an array of integers, where the same index is repeated several time

In [11]:
arr[ [2, 5, 7, 8, 5] ]

array([20, 50, 70, 80, 50])

New values can be assigned

In [12]:
arr[ [2, 8] ] = 500 

In [13]:
arr

array([  0,  10, 500,  30,  40,  50,  60,  70, 500,  90])

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/devdocs/user/quickstart.html#advanced-indexing-and-index-tricks">https://numpy.org/devdocs/user/quickstart.html#advanced-indexing-and-index-tricks</a><br>