# Copies and Views
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners.

In [3]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
new = arr[2:7] #shallow copy or view

In [6]:
new

array([2, 3, 4, 5, 6])

In [7]:
np.shares_memory(arr, new)

True

In [8]:
new[3] = 100

In [9]:
new

array([  2,   3,   4, 100,   6])

In [10]:
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
new = arr[2:7].copy()     #deep copy

In [14]:
new

array([2, 3, 4, 5, 6])

In [15]:
np.shares_memory(arr, new)

False

In [16]:
new[3] = 100

In [17]:
new

array([  2,   3,   4, 100,   6])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/devdocs/user/quickstart.html#copies-and-views">https://numpy.org/devdocs/user/quickstart.html#copies-and-views</a><br>