# Operations
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

## Element-Wise Operations

In [1]:
import numpy as np

In [8]:
a = np.arange(5)

In [9]:
a

array([0, 1, 2, 3, 4])

##### Arithmetic Operations

In [10]:
a+10

array([10, 11, 12, 13, 14])

In [11]:
b = np.ones(5)

In [12]:
b

array([1., 1., 1., 1., 1.])

In [13]:
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [14]:
a*b

array([0., 1., 2., 3., 4.])

In [15]:
a/b

array([0., 1., 2., 3., 4.])

In [16]:
b/a

C:\Users\imRohit46\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [17]:
a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
a.dot(a)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

##### Comparision Operations

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([6, 1, 2, 4])

In [24]:
a == b

array([False, False, False,  True])

In [25]:
a > b

array([False,  True,  True, False])

In [26]:
a < b

array([ True, False, False, False])

In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([6, 1, 2, 4])
c = np.array([1, 2, 3, 4])

In [28]:
np.array_equal(a,b)

False

In [29]:
np.array_equal(a,c)

True

##### Logical Operations

In [30]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [31]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [32]:
np.logical_and(a,b)

array([ True, False, False, False])

In [33]:
np.logical_not(a)

array([False, False,  True,  True])

##### Transcendental Functions

In [40]:
arr = np.arange(6)

In [41]:
print(arr)

[0 1 2 3 4 5]


In [42]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [43]:
np.log(arr)

C:\Users\imRohit46\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [44]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

##### Shape Mismatch

In [45]:
a = np.arange(5)

In [48]:
a

array([0, 1, 2, 3, 4])

In [47]:
b = np.array([1,2])

In [49]:
b

array([1, 2])

In [50]:
a + b

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [51]:
b = np.array([1, 2, 6, 8, 9])

In [52]:
a + b

array([ 1,  3,  8, 11, 13])

## Basic Reductions
##### Computing Sums

In [53]:
arr = np.array([5,8,3,6,7,9])

In [54]:
np.sum(arr)

38

In [55]:
arr = np.array([ [1,2,3],[4,5,6] ])

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [58]:
np.sum(arr, axis=1)

array([ 6, 15])

##### Min - Max

In [65]:
arr = np.array([50,88,30,60,76,92])

In [66]:
arr

array([50, 88, 30, 60, 76, 92])

In [67]:
np.min(arr)

30

In [68]:
np.max(arr)

92

In [69]:
np.argmin(arr)

2

In [70]:
np.argmax(arr)

5

##### Logical Operations

In [71]:
np.all([True, False, True, False])

False

In [72]:
np.all([True, True, True, True])

True

In [73]:
np.any([True, False, True, False])

True

In [74]:
np.any([False, False, False, False])

False

In [76]:
arr = np.zeros((5, 5))

In [77]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
np.any(arr != 0)

False

In [80]:
arr = np.array([50,88,30,60,76,92])

In [81]:
np.any(arr != 0)

True

In [84]:
arr = np.array([50,88,30,60,76,92])

In [85]:
np.any(arr == 0)

False

In [86]:
arr = np.array([50,88,30,0,76,92])

In [87]:
np.any(arr == 0)

True

In [89]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 3, 4])

In [90]:
np.all(a == b)

False

In [91]:
np.all( a != b )

False

In [95]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

In [96]:
np.all(a == b)

True

In [97]:
np.all(a != b)

False

In [101]:
a = np.array([1, 2, 3, 4])
b = np.array([6, 1, 2, 4])
c = np.array([1, 2, 3, 4])

In [102]:
((a <= b) & (b <= c)).all()

False

In [103]:
np.all( (a <= b) & (b <= c) )

False

##### Statistics

**1.Mean**

In [111]:
arr = np.arange(10)

In [112]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.mean(arr)

4.5

In [2]:
arr = np.array([[1, 2, 3], [5, 6, 1]])

In [3]:
arr

array([[1, 2, 3],
       [5, 6, 1]])

In [154]:
np.mean(arr)

3.0

In [155]:
np.mean(arr, axis=0)

array([3., 4., 2.])

In [156]:
np.mean(arr, axis=1)

array([2., 4.])

**2. Median**

In [157]:
arr = np.arange(10)

In [158]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.median(arr)

4.5

In [160]:
arr = np.array([[1, 2, 3], [5, 6, 1]])

In [161]:
arr

array([[1, 2, 3],
       [5, 6, 1]])

In [162]:
np.median(arr, axis=0)

array([3., 4., 2.])

In [163]:
np.median(arr, axis=1)

array([2., 5.])

In [164]:
arr = np.array([1,2,3,4,500])

In [165]:
arr

array([  1,   2,   3,   4, 500])

In [166]:
np.mean(arr)

102.0

In [167]:
np.median(arr)

3.0

**3. Standard Deviation**

In [139]:
arr = np.array([[1, 2, 3], [5, 6, 1]])

In [140]:
arr

array([[1, 2, 3],
       [5, 6, 1]])

In [141]:
np.std(arr)

1.9148542155126762

In [142]:
arr.std()

1.9148542155126762

In [143]:
np.std(arr, axis=0)

array([2., 2., 1.])

In [145]:
np.std(arr, axis=1)

array([0.81649658, 2.1602469 ])

In [146]:
arr.std(axis=0)

array([2., 2., 1.])

In [148]:
arr.std(axis=1)

array([0.81649658, 2.1602469 ])

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/doc/stable/user/quickstart.html#basic-operations">https://numpy.org/doc/stable/user/quickstart.html#basic-operations</a><br>