# Broadcasting
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

1. **Broadcasting** is a mechanism that allows NumPy to perform operations on arrays of different shapes. 
2. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. 
3. If the dimensions are not compatible, you will get a ValueError.

The image below gives an example of broadcasting:

<img src='broadcasting.png' width=600 height=600>

In [2]:
import numpy as np

In [5]:
arr = np.tile( np.arange(0, 20, 5), (3,1) )

In [6]:
arr

array([[ 0,  5, 10, 15],
       [ 0,  5, 10, 15],
       [ 0,  5, 10, 15]])

In [28]:
arr = arr.T

In [29]:
arr

array([[ 0,  0,  0],
       [ 5,  5,  5],
       [10, 10, 10],
       [15, 15, 15]])

In [30]:
b = np.array([1,2,3])

In [31]:
arr + b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [32]:
b = np.array([1,2])

In [33]:
arr + b

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [15]:
a = np.arange(0, 20, 5)
a

array([ 0,  5, 10, 15])

In [16]:
a.shape

(4,)

In [17]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array

In [18]:
a.shape

(4, 1)

In [19]:
a

array([[ 0],
       [ 5],
       [10],
       [15]])

In [20]:
b

array([1, 2, 3])

In [21]:
a + b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [22]:
a - b

array([[-1, -2, -3],
       [ 4,  3,  2],
       [ 9,  8,  7],
       [14, 13, 12]])

In [23]:
a * b

array([[ 0,  0,  0],
       [ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

In [24]:
a / b

array([[ 0.        ,  0.        ,  0.        ],
       [ 5.        ,  2.5       ,  1.66666667],
       [10.        ,  5.        ,  3.33333333],
       [15.        ,  7.5       ,  5.        ]])

<h3 style="color:green">Useful Links:</h3>
<a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">https://numpy.org/doc/stable/user/basics.broadcasting.html</a><br>