# Array Shape Manipulation
### by <a href='https://www.youtube.com/wonkyCode'>WonkyCode</a>

In [1]:
import numpy as np

##### Flattening

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr.ravel() #Return a flattened array.

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
arr.T.ravel()

array([1, 4, 2, 5, 3, 6])

##### Reshaping

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr.shape

(2, 3)

In [10]:
arr.reshape(3,2)    #Note: reshape may also return a copy

array([[1, 2],
       [3, 4],
       [5, 6]])

**ravel()** function simply returns a flattened view of Numpy array. 

**flatten()** function returns a flattened copy of Numpy array.

In [11]:
a = arr.ravel() #Return a flattened array.

In [12]:
b = arr.flatten() #Return a copy of the array collapsed into one dimension.

In [13]:
print(a)
print(b)
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [14]:
a[1] = 500

In [15]:
a

array([  1, 500,   3,   4,   5,   6])

In [16]:
arr

array([[  1, 500,   3],
       [  4,   5,   6]])

In [17]:
b

array([1, 2, 3, 4, 5, 6])

In [18]:
b[4] = 600

In [19]:
b

array([  1,   2,   3,   4, 600,   6])

In [20]:
arr

array([[  1, 500,   3],
       [  4,   5,   6]])

##### Adding a dimension

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [21]:
arr = np.array([1, 2, 3, 4, 5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr.shape

(5,)

In [24]:
b = arr[:, np.newaxis]

In [25]:
b.shape

(5, 1)

In [26]:
arr[0:3, np.newaxis]

array([[1],
       [2],
       [3]])

In [27]:
arr = np.array([ [1,2,3],[4,5,6] ])

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b = arr[:, np.newaxis]

In [30]:
b

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [31]:
b.shape

(2, 1, 3)

##### Dimension Shuffling

In [2]:
arr = np.arange(24)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
arr.shape

(24,)

In [35]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [36]:
arr.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [37]:
b = arr.reshape(6,4)

print(b)
print("--------------------")
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
(6, 4)


In [4]:
b = arr.reshape(4,2,3)

In [5]:
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [40]:
b.shape

(4, 2, 3)

##### Resizing
Change shape and size of array in-place.

In [41]:
arr = np.arange(5)

In [42]:
arr

array([0, 1, 2, 3, 4])

In [43]:
arr.resize( (10,) )

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [44]:
arr.resize((10,), refcheck=False)

In [45]:
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

In [46]:
zzz = arr.copy()

In [47]:
zzz.resize( (10,) )

In [48]:
zzz

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

In [49]:
d = zzz.copy()

In [50]:
d.resize((8,3))

In [51]:
d

array([[0, 1, 2],
       [3, 4, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
ccc = zzz

In [53]:
ccc.resize((8,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

##### Sorting Data

In [54]:
arr = np.array([[45, 89, 60], [20, 25, 38]])

In [55]:
arr

array([[45, 89, 60],
       [20, 25, 38]])

In [56]:
np.sort(arr) #Return a sorted copy of an array.

array([[45, 60, 89],
       [20, 25, 38]])

In [57]:
np.sort(arr, axis=0)

array([[20, 25, 38],
       [45, 89, 60]])

In [58]:
np.sort(arr, axis=1)

array([[45, 60, 89],
       [20, 25, 38]])

In [59]:
arr

array([[45, 89, 60],
       [20, 25, 38]])

In [60]:
arr.sort()

In [61]:
arr

array([[45, 60, 89],
       [20, 25, 38]])

In [62]:
arr.sort(axis=1)

In [63]:
arr

array([[45, 60, 89],
       [20, 25, 38]])

In [64]:
arr.sort(axis=0)

In [65]:
arr

array([[20, 25, 38],
       [45, 60, 89]])

In [66]:
#sorting with fancy indexing
arr = np.array([40, 30, 10, 20])

In [67]:
arr

array([40, 30, 10, 20])

In [68]:
b = np.argsort(arr)

In [69]:
b

array([2, 3, 1, 0], dtype=int64)

In [70]:
arr[b]

array([10, 20, 30, 40])

In [6]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [26]:
b=np.array([[[56,13,25],[78,65,14]],[[32,56,15],[12,45,35]]])

In [27]:
b

array([[[56, 13, 25],
        [78, 65, 14]],

       [[32, 56, 15],
        [12, 45, 35]]])

In [28]:
b.shape

(2, 2, 3)

In [31]:
np.sort(b)

array([[[13, 25, 56],
        [14, 65, 78]],

       [[15, 32, 56],
        [12, 35, 45]]])

In [34]:
np.sort(b, axis=0)

array([[[32, 13, 15],
        [12, 45, 14]],

       [[56, 56, 25],
        [78, 65, 35]]])

In [33]:
np.sort(b, axis=1)

array([[[56, 13, 14],
        [78, 65, 25]],

       [[12, 45, 15],
        [32, 56, 35]]])

array([[[32, 12, 14],
        [12, 45, 14]],

       [[56, 56, 25],
        [78, 65, 35]]])